using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using ShimmerAPI;

namespace ShimmerBluetoothTests
{
    /// <summary>
    /// Runs <see cref="TimestampUnwrap"/> against the conformance vectors shared by
    /// every Shimmer host API.
    /// <para>
    /// The vectors live in log-and-stream-common at
    /// Test/conformance/timestamp_unwrap.json, alongside the rule they encode
    /// (docs/SHIMMER3_STREAMING_DATA_FORMAT.md section 2.1) and the reference
    /// implementation that generates them. This project has no way to load a data
    /// file - the csproj is the old style, with no resource pipeline - so the array
    /// below is transcribed mechanically by
    /// <c>Test/host/crosscheck_timestamp_unwrap.py --emit csharp</c> rather than by
    /// hand. Regenerate it; do not edit it.
    /// </para>
    /// <para>
    /// The point of the shared file is that the Java driver, pyshimmer and the
    /// TypeScript web SDK run the same cases. Four implementations of one wire format
    /// drifted apart once already - the same unwrap defect sat in all four - and
    /// reviewing them against each other by hand is what let that happen. If this test
    /// and its counterparts disagree, one of the four is wrong.
    /// </para>
    /// <para>
    /// <see cref="TimestampUnwrapTest"/> covers the same rule in a form meant to be
    /// read; this one covers it in a form meant to be shared.
    /// </para>
    /// </summary>
    [TestClass]
    public class TimestampUnwrapVectorsTest
    {
        /// <summary>One shared vector: inputs, and what every host must produce.</summary>
        internal sealed class UnwrapVector
        {
            public readonly string Id;
            public readonly int Modulo;
            public readonly double ReorderWindowTicks;
            public readonly double[] Raw;
            public readonly double[] ExpectedUnwrapped;
            public readonly bool[] ExpectedRejected;
            public readonly double ExpectedFinalCycle;

            public UnwrapVector(string id, int modulo, double reorderWindowTicks,
                double[] raw, double[] expectedUnwrapped, bool[] expectedRejected,
                double expectedFinalCycle)
            {
                Id = id;
                Modulo = modulo;
                ReorderWindowTicks = reorderWindowTicks;
                Raw = raw;
                ExpectedUnwrapped = expectedUnwrapped;
                ExpectedRejected = expectedRejected;
                ExpectedFinalCycle = expectedFinalCycle;
            }
        }

        /// <summary>The revision of the vector file this test was transcribed from.</summary>
        private const int ExpectedRevision = 1;

        // Source: log-and-stream-common Test/conformance/timestamp_unwrap.json
        // revision 1, at commit 8e76966.
        // Generated by Test/host/crosscheck_timestamp_unwrap.py --emit csharp
        // Source: Test/conformance/timestamp_unwrap.json revision 1
        // Do not hand-edit; regenerate when the vector file changes.
        internal static readonly UnwrapVector[] Vectors =
        {
            new UnwrapVector(
                "monotonic-24bit",
                16777216, 520.0,
                new double[] { 1000, 1065, 1130 },
                new double[] { 1000, 1065, 1130 },
                new bool[] { false, false, false },
                0),
            new UnwrapVector(
                "wrap-24bit",
                16777216, 520.0,
                new double[] { 16777200, 16 },
                new double[] { 16777200, 16777232 },
                new bool[] { false, false },
                1),
            new UnwrapVector(
                "wrap-lands-on-zero-24bit",
                16777216, 520.0,
                new double[] { 16777116, 0 },
                new double[] { 16777116, 16777216 },
                new bool[] { false, false },
                1),
            new UnwrapVector(
                "invalid-zero-signature-24bit",
                16777216, 520.0,
                new double[] { 7406116, 7406506, 0, 7406571 },
                new double[] { 7406116, 7406506, 7406506, 7406571 },
                new bool[] { false, false, true, false },
                0),
            new UnwrapVector(
                "invalid-zero-no-cascade-24bit",
                16777216, 520.0,
                new double[] { 7406506, 0, 7406571, 7406636 },
                new double[] { 7406506, 7406506, 7406571, 7406636 },
                new bool[] { false, true, false, false },
                0),
            new UnwrapVector(
                "first-sample-zero-24bit",
                16777216, 520.0,
                new double[] { 0, 65, 130 },
                new double[] { 0, 65, 130 },
                new bool[] { false, false, false },
                0),
            new UnwrapVector(
                "wrap-16bit",
                65536, 5120.0,
                new double[] { 65436, 28 },
                new double[] { 65436, 65564 },
                new bool[] { false, false },
                1),
            new UnwrapVector(
                "zero-on-16bit-is-a-wrap",
                65536, 5120.0,
                new double[] { 30000, 0 },
                new double[] { 30000, 65536 },
                new bool[] { false, false },
                1),
            new UnwrapVector(
                "backward-step-outside-window-is-a-wrap-24bit",
                16777216, 520.0,
                new double[] { 7406506, 1 },
                new double[] { 7406506, 16777217 },
                new bool[] { false, false },
                1),
            new UnwrapVector(
                "duplicate-24bit",
                16777216, 520.0,
                new double[] { 1000, 1065, 1065, 1130 },
                new double[] { 1000, 1065, 1065, 1130 },
                new bool[] { false, false, false, false },
                0),
            new UnwrapVector(
                "reorder-one-period-24bit",
                16777216, 520.0,
                new double[] { 1000, 1130, 1065, 1195 },
                new double[] { 1000, 1130, 1065, 1195 },
                new bool[] { false, false, false, false },
                0),
            new UnwrapVector(
                "reorder-one-period-16bit",
                65536, 5120.0,
                new double[] { 40000, 41280, 40640, 41920 },
                new double[] { 40000, 41280, 40640, 41920 },
                new bool[] { false, false, false, false },
                0),
            new UnwrapVector(
                "reorder-across-wrap-boundary-24bit",
                16777216, 520.0,
                new double[] { 16777206, 5, 16777206, 70 },
                new double[] { 16777206, 16777221, 16777206, 16777286 },
                new bool[] { false, false, false, false },
                1),
            new UnwrapVector(
                "wrap-after-heavy-loss-24bit",
                16777216, 520.0,
                new double[] { 16000000, 100 },
                new double[] { 16000000, 16777316 },
                new bool[] { false, false },
                1),
            new UnwrapVector(
                "wrap-after-heavy-loss-16bit",
                65536, 5120.0,
                new double[] { 60000, 1000 },
                new double[] { 60000, 66536 },
                new bool[] { false, false },
                1),
            new UnwrapVector(
                "wrap-spanning-dropout-1p8s-16bit",
                65536, 5120.0,
                new double[] { 60000, 53446 },
                new double[] { 60000, 118982 },
                new bool[] { false, false },
                1),
            new UnwrapVector(
                "wrap-spanning-dropout-152s-24bit",
                16777216, 520.0,
                new double[] { 16000000, 4222784 },
                new double[] { 16000000, 21000000 },
                new bool[] { false, false },
                1),
            new UnwrapVector(
                "rate-unknown-backward-step-is-a-wrap-24bit",
                16777216, 0.0,
                new double[] { 1000, 1130, 1065, 1195 },
                new double[] { 1000, 1130, 16778281, 16778411 },
                new bool[] { false, false, false, false },
                1),
            new UnwrapVector(
                "rate-unknown-zero-still-rejected-24bit",
                16777216, 0.0,
                new double[] { 7406506, 0, 7406571 },
                new double[] { 7406506, 7406506, 7406571 },
                new bool[] { false, true, false },
                0),
            new UnwrapVector(
                "zero-within-window-of-origin-24bit",
                16777216, 520.0,
                new double[] { 300, 365, 0, 430 },
                new double[] { 300, 365, 0, 430 },
                new bool[] { false, false, false, false },
                0),
            new UnwrapVector(
                "zero-within-window-after-wrap-24bit",
                16777216, 520.0,
                new double[] { 16777100, 100, 165, 0, 230 },
                new double[] { 16777100, 16777316, 16777381, 16777216, 16777446 },
                new bool[] { false, false, false, false, false },
                1),
            new UnwrapVector(
                "reorder-window-boundary-inclusive-24bit",
                16777216, 512.0,
                new double[] { 10512, 10000 },
                new double[] { 10512, 10000 },
                new bool[] { false, false },
                0),
            new UnwrapVector(
                "reorder-window-boundary-exclusive-24bit",
                16777216, 512.0,
                new double[] { 10513, 10000 },
                new double[] { 10513, 16787216 },
                new bool[] { false, false },
                1),
            new UnwrapVector(
                "low-rate-clamp-16bit",
                65536, 8192.0,
                new double[] { 60000, 1000 },
                new double[] { 60000, 66536 },
                new bool[] { false, false },
                1),
            new UnwrapVector(
                "high-rate-reorder-24bit",
                16777216, 256.0,
                new double[] { 5000, 5032, 5000, 5064 },
                new double[] { 5000, 5032, 5000, 5064 },
                new bool[] { false, false, false, false },
                0),
            new UnwrapVector(
                "reorder-beyond-eight-periods-is-a-wrap-24bit",
                16777216, 256.0,
                new double[] { 5000, 5288, 5000 },
                new double[] { 5000, 5288, 16782216 },
                new bool[] { false, false, false },
                1),
        };

        internal const int VectorCount = 26;

        /// <summary>Feeds a series of raw values through the unwrapper, as a caller would.</summary>
        private class Unwrapper
        {
            public double LastUnwrapped;
            public double Cycle;
            public bool LastRejected;
            private readonly double _window;

            public Unwrapper(double window)
            {
                _window = window;
            }

            public double Feed(double rawTicks, int maxTicks)
            {
                TimestampUnwrap.Result r = TimestampUnwrap.Unwrap(
                    rawTicks, LastUnwrapped, Cycle, maxTicks, _window);
                LastRejected = r.Rejected;
                Cycle = r.Cycle;
                LastUnwrapped = r.Unwrapped;
                return r.Unwrapped;
            }
        }

        private static System.Collections.Generic.List<string> VectorIds()
        {
            var ids = new System.Collections.Generic.List<string>();
            foreach (UnwrapVector v in Vectors)
            {
                ids.Add(v.Id);
            }
            return ids;
        }

        [TestMethod]
        public void TestVectorSetIsComplete()
        {
            Assert.AreEqual(VectorCount, Vectors.Length,
                "the transcribed array and its count disagree - regenerate both with --emit csharp");
            Assert.AreEqual(1, ExpectedRevision,
                "vector file revision - update this test deliberately, not to make it pass");

            // Three vectors have to be here by name: each is the case that one
            // superseded rule gets wrong, so losing one would quietly stop covering it.
            CollectionAssert.Contains(VectorIds(), "wrap-spanning-dropout-1p8s-16bit");
            CollectionAssert.Contains(VectorIds(), "reorder-across-wrap-boundary-24bit");
            CollectionAssert.Contains(VectorIds(), "wrap-after-heavy-loss-24bit");
        }

        [TestMethod]
        public void TestAllSharedVectorsAgree()
        {
            foreach (UnwrapVector vector in Vectors)
            {
                Assert.AreEqual(vector.Raw.Length, vector.ExpectedUnwrapped.Length,
                    vector.Id + ": vector is self-consistent");
                Assert.AreEqual(vector.Raw.Length, vector.ExpectedRejected.Length,
                    vector.Id + ": vector is self-consistent");

                var u = new Unwrapper(vector.ReorderWindowTicks);
                for (int i = 0; i < vector.Raw.Length; i++)
                {
                    double got = u.Feed(vector.Raw[i], vector.Modulo);
                    string where = vector.Id + " [" + i + "] raw=" + vector.Raw[i];
                    Assert.AreEqual(vector.ExpectedUnwrapped[i], got, 0.0, where + ": unwrapped");
                    Assert.AreEqual(vector.ExpectedRejected[i], u.LastRejected, where + ": rejected");
                }
                Assert.AreEqual(vector.ExpectedFinalCycle, u.Cycle, 0.0, vector.Id + ": final cycle");
            }
        }

        /// <summary>
        /// The window derivations from the same file. Eight sample periods, in the
        /// 32768 Hz tick domain, clamped at a modulo/8 so a very low rate cannot leave
        /// every backward step looking like a reorder.
        /// </summary>
        [TestMethod]
        public void TestWindowDerivationCases()
        {
            int mod24 = TimestampUnwrap.TicksMax3Byte;
            const int mod16 = 65536;

            Assert.AreEqual(520.0, TimestampUnwrap.ReorderWindowTicks(32768.0 / 65, mod24), 1e-9,
                "504.123 Hz on the 3-byte counter");
            Assert.AreEqual(5120.0, TimestampUnwrap.ReorderWindowTicks(51.2, mod16), 1e-9,
                "51.2 Hz on the 2-byte counter");
            Assert.AreEqual(512.0, TimestampUnwrap.ReorderWindowTicks(512.0, mod24), 1e-9,
                "512 Hz");
            Assert.AreEqual(256.0, TimestampUnwrap.ReorderWindowTicks(1024.0, mod24), 1e-9,
                "1024 Hz");
            Assert.AreEqual(mod16 / 8.0, TimestampUnwrap.ReorderWindowTicks(1.0, mod16), 0.0,
                "1 Hz on the 2-byte counter is clamped");
            Assert.AreEqual(262144.0, TimestampUnwrap.ReorderWindowTicks(1.0, mod24), 1e-9,
                "1 Hz on the 3-byte counter is not");
            Assert.AreEqual(511.705088, TimestampUnwrap.ReorderWindowTicks(312500.0 / 610, mod24), 1e-4,
                "a TCXO rate, derived in the RTC tick domain and not the sampling clock");
        }

        /// <summary>
        /// The values the shared file cannot spell. An unknown rate arriving as a
        /// division result rather than as a literal zero is the case that matters: a
        /// host that lets it through produces an infinite window, which reads every
        /// backward step as a reorder and loses every wrap.
        /// </summary>
        [TestMethod]
        public void TestWindowIsZeroForEveryShapeOfUnknownRate()
        {
            int mod = TimestampUnwrap.TicksMax3Byte;
            Assert.AreEqual(0.0, TimestampUnwrap.ReorderWindowTicks(double.PositiveInfinity, mod), 0.0,
                "positive infinity");
            Assert.AreEqual(0.0, TimestampUnwrap.ReorderWindowTicks(double.NegativeInfinity, mod), 0.0,
                "negative infinity");
            Assert.AreEqual(0.0, TimestampUnwrap.ReorderWindowTicks(double.NaN, mod), 0.0, "NaN");
            Assert.AreEqual(0.0, TimestampUnwrap.ReorderWindowTicks(0.0, mod), 0.0, "zero");
            Assert.AreEqual(0.0, TimestampUnwrap.ReorderWindowTicks(-5.0, mod), 0.0, "negative");
        }
    }
}
